# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' bin_cv_loglik cpp
#'
#' LogLikilihood function for cv
#' 
#' @param x design matrix
#' @param beta vcm vector
#' @param y response vector
#' @param time vector
#' 
#' @export
#'
bin_cv_loglik <- function(x, beta, y, time) {
    .Call(`_tvcm_bin_cv_loglik`, x, beta, y, time)
}

#' bin_logit_loglik cpp
#'
#' LogLikilihood function for vcm
#' 
#' @param x design matrix
#' @param beta vcm vector
#' @param y response vector
#' @param time vector
#' @param time_zero grid point double
#' @param h bandwidth double
#' @param type kernel function int
#' 
#' @export
#'
bin_logit_loglik <- function(x, beta, y, time, time_zero, h, type) {
    .Call(`_tvcm_bin_logit_loglik`, x, beta, y, time, time_zero, h, type)
}

#' gr_logit_loglik cpp
#'
#' Gradient function for vcm
#' 
#' @param x design matrix
#' @param beta vcm vector
#' @param y response vector
#' @param time vector
#' @param time_zero grid point double
#' @param h bandwidth double
#' @param type kernel function int
#' 
#' @export
#'
gr_bin_logit_loglik <- function(x, beta, y, time, time_zero, h, type) {
    .Call(`_tvcm_gr_bin_logit_loglik`, x, beta, y, time, time_zero, h, type)
}

#' hs_logit_loglik cpp
#'
#' Hessian function for vcm
#' 
#' @param x design matrix
#' @param beta vcm vector
#' @param y response vector
#' @param time vector
#' @param time_zero grid point double
#' @param h bandwidth double
#' @param type kernel function int
#' 
#' @export
hs_bin_logit_loglik <- function(x, beta, y, time, time_zero, h, type) {
    .Call(`_tvcm_hs_bin_logit_loglik`, x, beta, y, time, time_zero, h, type)
}

#' kernel_function
#'
#' Computes the weight using a kernel function
#' 
#' @param time time point
#' @param time_zero grid point
#' @param h bandwidth
#' @param type kernel function
#' 
#' @export
#'
kernel_function <- function(time, time_zero, h, type) {
    .Call(`_tvcm_kernel_function`, time, time_zero, h, type)
}

#' kernel_vec
#'
#' Vectorized kernel function
#' 
#' @param time time point as a vector
#' @param time_zero grid point
#' @param h bandwidth
#' @param type kernel function
#' 
#' @export
#'
kernel_vec <- function(time, time_zero, h, type) {
    .Call(`_tvcm_kernel_vec`, time, time_zero, h, type)
}

#' pois_cv_loglik cpp
#'
#' LogLikelihood function for cv
#' 
#' @param x design matrix
#' @param beta vcm vector
#' @param y response vector
#' @param time vector
#' 
#' @export
#'
pois_cv_loglik <- function(x, beta, y, time) {
    .Call(`_tvcm_pois_cv_loglik`, x, beta, y, time)
}

#' pois_log_loglik cpp
#'
#' LogLikilihood function for vcm
#' 
#' @param x design matrix
#' @param beta vcm vector
#' @param y response vector
#' @param time vector
#' @param time_zero grid point double
#' @param h bandwidth double
#' @param type kernel function int
#' 
#' @export
#'
pois_log_loglik <- function(x, beta, y, time, time_zero, h, type) {
    .Call(`_tvcm_pois_log_loglik`, x, beta, y, time, time_zero, h, type)
}

#' gr_pois_log_loglik cpp
#'
#' Gradient function for vcm
#' 
#' @param x design matrix
#' @param beta vcm vector
#' @param y response vector
#' @param time vector
#' @param time_zero grid point double
#' @param h bandwidth double
#' @param type kernel function int
#' 
#' @export
#' 
gr_pois_log_loglik <- function(x, beta, y, time, time_zero, h, type) {
    .Call(`_tvcm_gr_pois_log_loglik`, x, beta, y, time, time_zero, h, type)
}

#' hs_pois_log_loglik cpp
#'
#' Hessian function for vcm
#' 
#' @param x design matrix
#' @param beta vcm vector
#' @param y response vector
#' @param time vector
#' @param time_zero grid point double
#' @param h bandwidth double
#' @param type kernel function int
#' 
#' @export
#' 
hs_pois_log_loglik <- function(x, beta, y, time, time_zero, h, type) {
    .Call(`_tvcm_hs_pois_log_loglik`, x, beta, y, time, time_zero, h, type)
}

#' vcm_wls cpp
#'
#' Weighted Least Squares Function
#' 
#' @param x design matrix
#' @param y response vector
#' @param time vector
#' @param time_zero grid point double
#' @param h bandwidth double
#' @param type kernel function int
#' 
#' @export
#'
vcm_wls <- function(x, y, time, time_zero, h, type) {
    .Call(`_tvcm_vcm_wls`, x, y, time, time_zero, h, type)
}

#' tvcm_wls cpp
#'
#' Weighted Least-Squares Function For Longitudinal Data
#' 
#' @param x design matrix
#' @param y response vector
#' @param time vector
#' @param id grouping vector
#' @param time_zero grid point double
#' @param h bandwidth double
#' @param type kernel function int
#' 
#' @export
#'
tvcm_wls <- function(x, y, time, id, time_zero, h, type) {
    .Call(`_tvcm_tvcm_wls`, x, y, time, id, time_zero, h, type)
}

